package model;

/**
 * https://www.twilio.com/docs/api/twiml/record
 * 
 * Twilio will pass the following parameters with its request to the 'recordingStatusCallback' URL:
 * 
 * PARAMETER	DESCRIPTION
 * TranscriptionSid	The unique 34 character ID of the transcription.
 * TranscriptionText	Contains the text of the transcription.
 * TranscriptionStatus	The status of the transcription attempt: either 'completed' or 'failed'.
 * TranscriptionUrl	The URL for the transcription's REST API resource.
 * RecordingSid	The unique 34 character ID of the recording from which the transcription was generated.
 * RecordingUrl	The URL for the transcription's source recording resource.
 * CallSid	A unique identifier for this call, generated by Twilio.
 * AccountSid	Your Twilio account id. It is 34 characters long, and always starts with the letters AC.
 * From	The phone number or client identifier of the party that initiated the call. 
 *      Phone numbers are formatted with a '+' and country code, e.g. +16175551212 ([E.164][e164] format). 
 *      Client identifiers begin with the client: URI scheme; for example, for a call from a client 
 *      named 'tommy', the From parameter will be client:tommy.
 * To	The phone number or client identifier of the called party. 
 *      Phone numbers are formatted with a '+' and country code, e.g. +16175551212 ([E.164][e164] format). 
 *      Client identifiers begin with the client: URI scheme; for example, for a call to a client 
 *      named 'jenny', the To parameter will be client:jenny.
 * CallStatus	A descriptive status for the call. The value is one of queued, ringing, in-progress, 
 *              completed, busy, failed or no-answer. See the CallStatus section for more details.
 * ApiVersion	The version of the Twilio API used to handle this call. For incoming calls, this is 
 *              determined by the API version set on the called number. For outgoing calls, this is 
 *              the API version used by the outgoing call's REST API request.
 * Direction	A string describing the direction of the call. inbound for inbound calls, outbound-api 
 *              for calls initiated via the REST API or outbound-dial for calls initiated by a <Dial> verb.
 * ForwardedFrom	This parameter is set only when Twilio receives a forwarded call, but its value 
 *                  depends on the caller's carrier including information when forwarding. 
 *                  Not all carriers support passing this information.
 */
public class RecordingStatusCallback {
	public String recordingSid;
	public String recordingUrl;
	public String callSid;
	public String from;
	public String to;
	public String callStatus;
	public String apiVersion;
	public String direction;
	public String forwardedFrom;
	
	public RecordingStatusCallback() {
		super();
	}
	
	public RecordingStatusCallback(String sid, String url, String csid, String f, String t, 
			String status, String av, String d, String forwarded) {
		super();
		recordingSid = sid;
		recordingUrl = url;
		callSid = csid;
		from = f;
		to = t;
		callStatus = status;
		apiVersion = av;
		direction = d;
		forwardedFrom = forwarded;
	}

	@Override
	public String toString() {
		return "RecordingStatusCallback [recordingSid=" + recordingSid + ", recordingUrl=" + recordingUrl
				+ ", callSid=" + callSid + ", from=" + from + ", to=" + to + ", callStatus=" + callStatus
				+ ", apiVersion=" + apiVersion + ", direction=" + direction + ", forwardedFrom=" + forwardedFrom + "]";
	}
}
